// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("rescript/lib/js/caml_option.js");
var Graphql_facade = require("./graphql_facade");

var UnionMembers = {};

function parse(prim) {
  return Graphql_facade.wrapClassType(prim);
}

var Named = {
  parse: parse
};

function parse$1(prim) {
  return Graphql_facade.wrapClassType(prim);
}

function parse_nn(prim) {
  return Graphql_facade.wrapClassType(prim);
}

var Input = {
  parse: parse$1,
  parse_nn: parse_nn
};

function parse$2(prim) {
  return Graphql_facade.wrapClassType(prim);
}

function parse_nn$1(prim) {
  return Graphql_facade.wrapClassType(prim);
}

var Output = {
  parse: parse$2,
  parse_nn: parse_nn$1
};

function name(t) {
  return t.name;
}

function description(t) {
  return Caml_option.null_to_opt(t.description);
}

function type_(t) {
  return t.type;
}

function defaultValue(t) {
  return t.defaultValue;
}

function astNode(t) {
  return Caml_option.null_to_opt(t.astNode);
}

var Argument = {
  name: name,
  description: description,
  type_: type_,
  defaultValue: defaultValue,
  astNode: astNode
};

function name$1(t) {
  return t.name;
}

function description$1(t) {
  return Caml_option.null_to_opt(t.description);
}

function type_$1(t) {
  return t.type;
}

function args(t) {
  return t.args;
}

function isDeprecated(t) {
  return t.isDeprecated;
}

function deprecationReason(t) {
  return Caml_option.nullable_to_opt(t.deprecationReason);
}

function astNode$1(t) {
  return Caml_option.nullable_to_opt(t.astNode);
}

var Field = {
  name: name$1,
  description: description$1,
  type_: type_$1,
  args: args,
  isDeprecated: isDeprecated,
  deprecationReason: deprecationReason,
  astNode: astNode$1
};

function name$2(t) {
  return t.name;
}

function description$2(t) {
  return Caml_option.null_to_opt(t.description);
}

function locations(t) {
  return t.locations;
}

function isRepeatable(t) {
  return t.isRepeatable;
}

function args$1(t) {
  return t.args;
}

function astNode$2(t) {
  return Caml_option.null_to_opt(t.astNode);
}

var Directive = {
  name: name$2,
  description: description$2,
  locations: locations,
  isRepeatable: isRepeatable,
  args: args$1,
  astNode: astNode$2
};

function name$3(t) {
  return t.name;
}

function description$3(t) {
  return Caml_option.null_to_opt(t.description);
}

function astNode$3(t) {
  return Caml_option.null_to_opt(t.astNode);
}

function extensionASTNodes(t) {
  return Caml_option.null_to_opt(t.extensionASTNodes);
}

var Scalar = {
  name: name$3,
  description: description$3,
  astNode: astNode$3,
  extensionASTNodes: extensionASTNodes
};

function name$4(t) {
  return t.name;
}

function description$4(t) {
  return Caml_option.null_to_opt(t.description);
}

function astNode$4(t) {
  return Caml_option.null_to_opt(t.astNode);
}

function extensionASTNodes$1(t) {
  return Caml_option.null_to_opt(t.extensionASTNodes);
}

function name$5(t) {
  return t.name;
}

function description$5(t) {
  return Caml_option.null_to_opt(t.description);
}

function astNode$5(t) {
  return Caml_option.null_to_opt(t.astNode);
}

function extensionASTNodes$2(t) {
  return Caml_option.null_to_opt(t.extensionASTNodes);
}

function name$6(t) {
  return t.name;
}

function description$6(t) {
  return Caml_option.null_to_opt(t.description);
}

function astNode$6(t) {
  return Caml_option.null_to_opt(t.astNode);
}

function extensionASTNodes$3(t) {
  return Caml_option.null_to_opt(t.extensionASTNodes);
}

function name$7(t) {
  return t.name;
}

function description$7(t) {
  return Caml_option.null_to_opt(t.description);
}

function value(t) {
  return t.value;
}

function isDeprecated$1(t) {
  return t.isDeprecated;
}

function deprecationReason$1(t) {
  return Caml_option.null_to_opt(t.deprecationReason);
}

function astNode$7(t) {
  return Caml_option.nullable_to_opt(t.astNode);
}

var EnumValue = {
  name: name$7,
  description: description$7,
  value: value,
  isDeprecated: isDeprecated$1,
  deprecationReason: deprecationReason$1,
  astNode: astNode$7
};

function name$8(t) {
  return t.name;
}

function description$8(t) {
  return Caml_option.null_to_opt(t.description);
}

function astNode$8(t) {
  return Caml_option.null_to_opt(t.astNode);
}

function extensionASTNodes$4(t) {
  return Caml_option.null_to_opt(t.extensionASTNodes);
}

function getValue(t, s) {
  return Caml_option.null_to_opt(t.getValue(s));
}

function name$9(t) {
  return t.name;
}

function description$9(t) {
  return Caml_option.nullable_to_opt(t.description);
}

function type_$2(t) {
  return t.type;
}

function defaultValue$1(t) {
  return t.defaultValue;
}

function astNode$9(t) {
  return Caml_option.nullable_to_opt(t.astNode);
}

var InputField = {
  name: name$9,
  description: description$9,
  type_: type_$2,
  defaultValue: defaultValue$1,
  astNode: astNode$9
};

function name$10(t) {
  return t.name;
}

function description$10(t) {
  return Caml_option.null_to_opt(t.description);
}

function astNode$10(t) {
  return Caml_option.null_to_opt(t.astNode);
}

function extensionASTNodes$5(t) {
  return Caml_option.null_to_opt(t.extensionASTNodes);
}

function astNode$11(t) {
  return Caml_option.null_to_opt(t.astNode);
}

function extensionASTNodes$6(t) {
  return Caml_option.null_to_opt(t.extensionASTNodes);
}

var Abstract = {};

function Object_getFields(prim) {
  return prim.getFields();
}

function Object_getInterfaces(prim) {
  return prim.getInterfaces();
}

var $$Object = {
  name: name$4,
  description: description$4,
  astNode: astNode$4,
  extensionASTNodes: extensionASTNodes$1,
  getFields: Object_getFields,
  getInterfaces: Object_getInterfaces
};

function Interface_getFields(prim) {
  return prim.getFields();
}

function Interface_toAbstract(prim) {
  return prim;
}

var Interface = {
  name: name$5,
  description: description$5,
  astNode: astNode$5,
  extensionASTNodes: extensionASTNodes$2,
  getFields: Interface_getFields,
  toAbstract: Interface_toAbstract
};

function Union_getTypes(prim) {
  return prim.getTypes();
}

function Union_toAbstract(prim) {
  return prim;
}

var Union = {
  name: name$6,
  description: description$6,
  astNode: astNode$6,
  extensionASTNodes: extensionASTNodes$3,
  getTypes: Union_getTypes,
  toAbstract: Union_toAbstract
};

function Enum_getValues(prim) {
  return prim.getValues();
}

var Enum = {
  name: name$8,
  description: description$8,
  astNode: astNode$8,
  extensionASTNodes: extensionASTNodes$4,
  getValues: Enum_getValues,
  getValue: getValue
};

function InputObject_getFields(prim) {
  return prim.getFields();
}

var InputObject = {
  name: name$10,
  description: description$10,
  astNode: astNode$10,
  extensionASTNodes: extensionASTNodes$5,
  getFields: InputObject_getFields
};

function getQueryType(prim) {
  return Caml_option.nullable_to_opt(prim.getQueryType());
}

function getMutationType(prim) {
  return Caml_option.nullable_to_opt(prim.getMutationType());
}

function getSubscriptionType(prim) {
  return Caml_option.nullable_to_opt(prim.getSubscriptionType());
}

function getTypeMap(prim) {
  return prim.getTypeMap();
}

function getType(prim0, prim1) {
  return Caml_option.nullable_to_opt(prim0.getType(prim1));
}

function getPossibleTypes(prim0, prim1) {
  return prim0.getPossibleTypes(prim1);
}

function isPossibleType(prim0, prim1, prim2) {
  return prim0.isPossibleType(prim1, prim2);
}

function getDirectives(prim) {
  return prim.getDirectives();
}

function getDirective(prim0, prim1) {
  return Caml_option.nullable_to_opt(prim0.getDirectives(prim1));
}

exports.UnionMembers = UnionMembers;
exports.Named = Named;
exports.Abstract = Abstract;
exports.Input = Input;
exports.Output = Output;
exports.Argument = Argument;
exports.Field = Field;
exports.Directive = Directive;
exports.Scalar = Scalar;
exports.$$Object = $$Object;
exports.Interface = Interface;
exports.Union = Union;
exports.EnumValue = EnumValue;
exports.Enum = Enum;
exports.InputField = InputField;
exports.InputObject = InputObject;
exports.astNode = astNode$11;
exports.extensionASTNodes = extensionASTNodes$6;
exports.getQueryType = getQueryType;
exports.getMutationType = getMutationType;
exports.getSubscriptionType = getSubscriptionType;
exports.getTypeMap = getTypeMap;
exports.getType = getType;
exports.getPossibleTypes = getPossibleTypes;
exports.isPossibleType = isPossibleType;
exports.getDirectives = getDirectives;
exports.getDirective = getDirective;
/* ./graphql_facade Not a pure module */
