// Generated by ReScript, PLEASE EDIT WITH CARE


var DirectiveLocation = {};

var TypeKind = {};

var ConflictAction = {};

var OrderBy = {};

var UsersConstraint = {};

var UsersSelectColumn = {};

var UsersUpdateColumn = {};

var CapsulesFind = {};

var CoresFind = {};

var HistoryFind = {};

var LaunchFind = {};

var MissionsFind = {};

var PayloadsFind = {};

var ShipsFind = {};

var StringComparisonExp = {};

var TimestamptzComparisonExp = {};

var UsersInsertInput = {};

var UsersMaxOrderBy = {};

var UsersMinOrderBy = {};

var UsersOnConflict = {};

var UsersOrderBy = {};

var UsersSetInput = {};

var UuidComparisonExp = {};

var UsersAggregateOrderBy = {};

var UsersArrRelInsertInput = {};

var UsersObjRelInsertInput = {};

var Tester = {};

var UsersBoolExp;

export {
  DirectiveLocation ,
  TypeKind ,
  ConflictAction ,
  OrderBy ,
  UsersConstraint ,
  UsersSelectColumn ,
  UsersUpdateColumn ,
  CapsulesFind ,
  CoresFind ,
  HistoryFind ,
  LaunchFind ,
  MissionsFind ,
  PayloadsFind ,
  ShipsFind ,
  StringComparisonExp ,
  TimestamptzComparisonExp ,
  UsersInsertInput ,
  UsersMaxOrderBy ,
  UsersMinOrderBy ,
  UsersOnConflict ,
  UsersOrderBy ,
  UsersSetInput ,
  UuidComparisonExp ,
  UsersAggregateOrderBy ,
  UsersArrRelInsertInput ,
  UsersObjRelInsertInput ,
  UsersBoolExp ,
  Tester ,
}
/* No side effect */
