// Generated by ReScript, PLEASE EDIT WITH CARE


var $$Boolean = {};

var $$Date = {};

var Float = {};

var Id = {};

var Int = {};

var $$String = {};

var Timestamptz = {};

var Uuid = {};

export {
  $$Boolean ,
  $$Date ,
  Float ,
  Id ,
  Int ,
  $$String ,
  Timestamptz ,
  Uuid ,
}
/* No side effect */
