// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var PluginOutput = {};

var AddToSchemaResult = {};

exports.PluginOutput = PluginOutput;
exports.AddToSchemaResult = AddToSchemaResult;
/* No side effect */
