// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


async function default_plugin(schema, documents, param) {
  return "";
}

var $$default = {
  plugin: default_plugin
};

exports.default = $$default;
exports.__esModule = true;
/* No side effect */
