// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Core__List = require("@rescript/core/src/Core__List.bs.js");
var Schema$Graphql = require("@re-graphql-codegen/graphql/src/Schema.bs.js");
var Caml_exceptions = require("rescript/lib/js/caml_exceptions.js");

function WithGqlWrapper(Base) {
  return {};
}

var BaseInput = {};

var InputType = {};

function fromDefinitions(definitions) {
  return Core__List.fromArray(definitions.toReversed().map(function (d) {
                  return {
                          TAG: "PrintDefinition",
                          _0: d
                        };
                }));
}

var Unknown_type = /* @__PURE__ */Caml_exceptions.create("WorkItem-GraphqlCodegenOperations.Unknown_type");

var Non_input_type = /* @__PURE__ */Caml_exceptions.create("WorkItem-GraphqlCodegenOperations.Non_input_type");

function $$process(t, schema) {
  
}

exports.WithGqlWrapper = WithGqlWrapper;
exports.BaseInput = BaseInput;
exports.InputType = InputType;
exports.fromDefinitions = fromDefinitions;
exports.Unknown_type = Unknown_type;
exports.Non_input_type = Non_input_type;
exports.$$process = $$process;
/* Schema-Graphql Not a pure module */
