// Generated by ReScript, PLEASE EDIT WITH CARE


var MissionInfo = {
  $$document: "\n    fragment MissionInfo on CapsuleMission {\n      flight\n      name\n      __typename\n    }\n  "
};

export {
  MissionInfo ,
}
/* No side effect */
