// Generated by ReScript, PLEASE EDIT WITH CARE


var Get_union = {};

var Union = {
  $$document: "\n    query Union {\n      get_union {\n        ... on MemberA {\n          id\n          a\n          __typename\n        }\n        __typename\n      }\n    }\n  ",
  Get_union: Get_union
};

export {
  Union ,
}
/* No side effect */
