// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WrapperMjs from "./wrapper.mjs";
import * as OptionPlus$GraphqlCodegenOperations from "./OptionPlus.mjs";

function filePathMatchesPatterns(prim0, prim1) {
  return WrapperMjs.testPattern(prim0, prim1);
}

var SchemaPatterns = {
  filePathMatchesPatterns: filePathMatchesPatterns
};

function getGeneratesEntry(prim) {
  return WrapperMjs.getGeneratesEntry(prim);
}

function getSchemaPatterns(prim) {
  return WrapperMjs.getSchemaPatterns(prim);
}

var CodegenConfig = {
  getGeneratesEntry: getGeneratesEntry,
  getSchemaPatterns: getSchemaPatterns
};

function getCodegenConfig(prim) {
  return WrapperMjs.getCodegenConfig(prim);
}

async function getConfig(configFilePath) {
  var match = OptionPlus$GraphqlCodegenOperations.getOrPanic(await WrapperMjs.getCodegenConfig(configFilePath), "Codegen config not found");
  var mainConfig = match[1];
  var generatesEntry = OptionPlus$GraphqlCodegenOperations.getOrPanic(WrapperMjs.getGeneratesEntry(mainConfig), "Missing ppxGenerates property in codegen config");
  return [
          {
            mainConfig: mainConfig,
            generatesEntry: generatesEntry
          },
          match[0],
          WrapperMjs.getSchemaPatterns(mainConfig)
        ];
}

function runBase(prim) {
  return WrapperMjs.runBase(prim);
}

function runDocument(prim0, prim1, prim2) {
  return WrapperMjs.runDocument(prim0, prim1, prim2);
}

export {
  SchemaPatterns ,
  CodegenConfig ,
  getCodegenConfig ,
  getConfig ,
  runBase ,
  runDocument ,
}
/* ./wrapper.mjs Not a pure module */
