// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as RescriptCore from "@rescript/core/src/RescriptCore.mjs";

function getOrPanic(opt, str) {
  if (opt !== undefined) {
    return Caml_option.valFromOption(opt);
  } else {
    return RescriptCore.panic(str);
  }
}

export {
  getOrPanic ,
}
/* No side effect */
