// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "../../../node_modules/rescript/lib/es6/js_dict.js";
import * as Cli from "@graphql-codegen/cli";

function run(schema, pluginName, scalarModule, baseTypesModule, inputSdl, filePath) {
  return Cli.generate({
              schema: schema,
              config: {
                baseTypesModule: baseTypesModule,
                scalarModule: scalarModule
              },
              generates: Js_dict.fromArray([[
                      filePath,
                      {
                        plugins: [pluginName],
                        documents: inputSdl
                      }
                    ]])
            }, false);
}

export {
  run ,
}
/* @graphql-codegen/cli Not a pure module */
