// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("rescript/lib/js/js_dict.js");
var Cli = require("@graphql-codegen/cli");

function $$default(schema, pluginName) {
  return function (inputSdl, file_path) {
    Cli.generate({
          schema: schema,
          documents: inputSdl,
          generates: Js_dict.fromArray([[
                  file_path,
                  {
                    plugins: [pluginName]
                  }
                ]])
        }, true);
  };
}

exports.default = $$default;
exports.__esModule = true;
/* @graphql-codegen/cli Not a pure module */
